# Application configuration file.

env: prod       # mode (values: prod, dev, test)
assets: assets  # assets folder name (required)
admin: admin    # admin folder name (optional)
key: ''         # licence key (optional)

db:
    host: localhost             # database host name or ip address
    driver: sqlite              # database driver. (values: mysql, pgsql, sqlite, oracle)
    database: ''                # database name
    username: root              # database username
    password: ''                # database user password
    charset: utf8               # database charset
    collation: utf8_general_ci  # database charset collation
    prefix: ''                  # database tables prefix

smtp:
    host: smtp.localhost        # smtp host name or ip address
    port: 587                   # smtp port
    username: root              # smtp username
    password: ''                # smtp user password
    encryption: tls             # smtp encryption
    charset: utf-8              # charset
    from:
        address: hello@localhost    # default sender e-mail
        name: Example               # default sender name

autoload:
    helper: []
    library: []
    model: []
    
timezone: Europe/Istanbul   # date/time timezone 
salt: ''                    # token salt value 
https: false                # default URI Scheme

services:       # [provider, facade]
    Load:       ['Nur\Load\Load',                        'Nur\Facades\Load']
    AutoLoad:   ['Nur\Load\AutoLoad',                    'Nur\Facades\AutoLoad']
    Uri:        ['Nur\Uri\Uri',                          'Nur\Facades\Uri']
    Request:    ['Nur\Http\Request',                     'Nur\Facades\Request']
    Response:   ['Nur\Http\Response',                    'Nur\Facades\Response']
    Http:       ['Nur\Http\Http',                        'Nur\Facades\Http']
    Cookie:     ['Nur\Http\Cookie',                      'Nur\Facades\Cookie']
    Session:    ['Nur\Http\Session',                     'Nur\Facades\Session']
    Route:      ['Nur\Router\Route',                     'Nur\Facades\Route']
    Builder:    ['Nur\Database\Builder',                 'Nur\Facades\Builder']
    Sql:        ['Nur\Database\Sql',                     'Nur\Facades\Sql']
    Blade:      ['Nur\Blade\Blade',                      'Nur\Facades\Blade']    
    Log:        ['Nur\Log\Log',                          'Nur\Facades\Log']
    Html:       ['Nur\Components\Builder\Html',          'Nur\Facades\Html']
    Form:       ['Nur\Components\Builder\Form',          'Nur\Facades\Form']
    Cache:      ['Nur\Components\Cache\Cache',           'Nur\Facades\Cache']
    Mail:       ['Nur\Components\Mail\Mail',             'Nur\Facades\Mail']
    Upload:     ['Nur\Components\Upload\Upload',         'Nur\Facades\Upload']
    Validation: ['Nur\Components\Validation\Validation', 'Nur\Facades\Validation']
